# fly.toml app configuration file generated for rippou-ripple-web on 2025-04-15T08:20:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rippou-ripple-web'
primary_region = 'hkg'

[mounts]
source="member_access"
destination="/database"

[env]
DOMAIN_NAME = "https://rippou-ripple-web.fly.dev"
DATABASE_PATH = "/database"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
